### ISSUE TITLE
Highscore.txt: FileNotFoundError: No such file or directory

### ISSUE THREAD

**Issue by Furbinator** [Aeryes/Demented#6] opened 2018-04-28 13:15 UTC
I'm trying to get your game working, but the code hits an exception trying to a file to read the contents.
C:\\Users\\Anon\\Desktop\\Demented-master\\highscore.txt

**Comment by Aeryes** [comment] 2018-04-28 15:47
I know what the issue is. Thank you for bringing it to light. I'll fix the path issues later today.

**Comment by Aeryes** [comment] 2018-04-28 15:54
Okay can you try and run it now? It should be fixed. Just make sure the contents are all in the one folder.

**Closed as completed** 2018-06-27 21:12 UTC
